n1=248
d1=1
o1=1
in="/home/bsc21/bsc21964/scratch/bsc_usct/rx.H@"


Scale:   bsc21964@login1   Wed Sep  4 12:29:09 2019
		sets next: in="/home/bsc21/bsc21964/scratch/Scale@Jc9jpS"
		dscale=1000
		data_format="xdr_float"


Cat3d:   bsc21964@login1   Wed Sep  4 13:05:50 2019
		sepstr_ready_out() : sets next in="stdin"
		axis=2
		file1="./Geom/rx_mm.H"
		file2="./Geom/rz_mm.H"
		junkME=0
	n2=2  o2=0.000000  d2=1.000000
		gff="-1"
		hff="-1"
hff=-1 gff=-1  n9=1 
	n1=248  o1=1.000000  d1=1.000000   label1="Undefined"   unit1="Undefined"
		hff="-1"
		gff="-1"
		esize=4
		data_format="xdr_float"


Window3d:   bsc21964@login1   Wed Sep  4 13:05:50 2019
		sets next: in="/home/bsc21/bsc21964/scratch/Window3d@kCwtB7"
#Window #f1=170  #j1=1 #n1=31
#Window #f2=0  #j2=1 #n2=2
		junkME=0
	n2=2  o2=0.000000  d2=1.000000   label2="Undefined"   unit2="Undefined"
		gff="-1"
		hff="-1"
hff=-1 gff=-1  n9=1 
	n1=31  o1=171.000000  d1=1.000000   label1="Undefined"   unit1="Undefined"
		hff="-1"
		gff="-1"
		esize=4
		data_format="xdr_float"

