

:   root@5156012cf43f   Fri Apr 30 19:44:21 2021
	 	n1=1500 o1=0 d1=0.002 label1="" 

	 	n2=100 o2=-100 d2=11 label2="" 

	 	n3=100 o3=-100 d3=11 label3="" 

	 	n4=1 o4=100 d4=100 label4="" 

	 	n5=1 o5=0 d5=1 label5="none" 

	 	n6=1 o6=0 d6=1 label6="none" 

	 	n7=1 o7=0 d7=1 label7="none" 

	 	n8=1 o8=0 d8=1 label8="none" 

		esize=4
		sets next: in="/Users/rustam/Documents/research/scratch/const_wavefield_two.H@"
		data_format="xdr_float"
