Input from a tty

Gauss:   arustam@oas.stanford.edu   Wed Aug 29 11:58:56 2018
		sepstr_ready_out() : sets next in="stdin"
		From par: n1=100
		From par: n2=100
		From par: n3=1
		From par: ngauss=1
		From par: velback=0
		From par: o1=0
		From par: o2=0
		From par: o3=0
		From par: d1=1
		From par: d2=1
		From par: d3=1
	 	n1=100 o1=0 d1=1 label1="" 

	 	n2=100 o2=0 d2=1 label2="" 

	 	n3=1 o3=0 d3=1 label3="" 

		Read  from param: #zero_at=1e+17
	 	n1=100 o1=0 d1=1 label1="" 

	 	n2=100 o2=0 d2=1 label2="" 

	 	n3=1 o3=0 d3=1 label3="" 

		data_format="xdr_float"


Pad:   arustam@oas.stanford.edu   Wed Aug 29 11:58:56 2018
		sets next: in="/homes/sep/arustam/scratch/Pad@7QGLyl"
	 	n1=200 o1=-50 d1=1 label1="" 

		#beg=50
		#end=50
	 	n2=300 o2=-100 d2=1 label2="" 

		#beg=100
		#end=100
		data_format="xdr_float"

