

:   root@ce15a5191c99   Mon Sep 26 20:50:07 2022
	 	n1=1500 o1=0 d1=0.002 label1="" 

	 	n2=200 o2=0 d2=10 label2="" 

	 	n3=10 o3=100 d3=100 label3="" 

	 	n4=1 o4=0 d4=1 label4="none" 

	 	n5=1 o5=0 d5=1 label5="none" 

	 	n6=1 o6=0 d6=1 label6="none" 

	 	n7=1 o7=0 d7=1 label7="none" 

	 	n8=1 o8=0 d8=1 label8="none" 

		esize=4
		sets next: in="/home/scratch/ph1.H@"
		data_format="xdr_float"
