

./test/checkWEM.x:   arustam@oas.stanford.edu   Thu Aug 30 16:06:25 2018
	 	n1=500 o1=0 d1=0.002 label1="" 

	 	n2=300 o2=-10 d2=0.1 label2="" 

	 	n3=200 o3=-5 d3=0.1 label3="" 

	 	n4=1 o4=0 d4=1 label4="none" 

	 	n5=1 o5=0 d5=1 label5="none" 

	 	n6=1 o6=0 d6=1 label6="none" 

	 	n7=1 o7=0 d7=1 label7="none" 

	 	n8=1 o8=0 d8=1 label8="none" 

		sets next: in="/homes/sep/arustam/scratch/wfld1.H@"
		data_format="xdr_float"
