Input from a tty

Wavelet:   user@e50d93c8f46e   Tue Apr  9 23:55:01 2019
		sets next: in="/home/user/project/scratch/wave.H@"
		n2=1
		n3=1
		o1=0
	Wavelet generation
		esize=4
		ascii="n"
		given n1=1000
	given n1 not a power of 2, new n1 computed

		computed n1=1024
		d1=0.002
		n1=1000
		domain="time"
		n1wavelet=1024
		d1wavelet=0.002
		domainwavelet="time"
		wavelet="ricker2"
		phase="minimum"
		degrees=0
		fund=40
		flow=10
		fhigh=60
		order=6
		orderlow=6
		orderhigh=6
		tdelay=0
		bell=0.512
		boxcar=2.048
		data_format="xdr_float"



Window3d:   user@e50d93c8f46e   Tue Apr  9 23:58:54 2019
		sets next: in="/home/user/project/scratch/wwave.H@"
#Window #f1=0  #j1=1 #n1=500
		junkME=0
		gff="-1"
		hff="-1"
hff=-1 gff=-1  n9=1 
	n1=500  o1=0.000000  d1=0.002000   label1="Undefined"   unit1="Undefined"
		hff="-1"
		gff="-1"
		esize=4
		data_format="xdr_float"

