Input from a tty

Gauss:   arustam@oas.stanford.edu   Sun Aug  5 21:13:57 2018
		sets next: in="/homes/sep/arustam/scratch/Gauss@cpAYOB"
		From par: n1=50
		From par: n2=2
		From par: n3=1
		From par: ngauss=1
		From par: velback=0
		From par: o1=-20
		From par: o2=0
		From par: o3=0
		From par: d1=1
		From par: d2=1
		From par: d3=1
	 	n1=50 o1=-20 d1=1 label1="" 

	 	n2=2 o2=0 d2=1 label2="" 

	 	n3=1 o3=0 d3=1 label3="" 

		Read  from param: #zero_at=1e+17
	 	n1=50 o1=-20 d1=1 label1="" 

	 	n2=2 o2=0 d2=1 label2="" 

	 	n3=1 o3=0 d3=1 label3="" 

		data_format="xdr_float"
