Input from a tty

Wavelet:   arustam@oas.stanford.edu   Mon Aug  6 09:14:13 2018
		sets next: in="/homes/sep/arustam/scratch/Wavelet@dTdtA7"
		n2=1
		n3=1
		o1=0
	Wavelet generation
		esize=4
		ascii="n"
		given n1=200
	given n1 not a power of 2, new n1 computed

		computed n1=256
		d1=0.002
		n1=200
		domain="time"
		n1wavelet=256
		d1wavelet=0.002
		domainwavelet="time"
		wavelet="ricker2"
		phase="minimum"
		degrees=0
		fund=40
		flow=10
		fhigh=60
		order=6
		orderlow=6
		orderhigh=6
		tdelay=0
		bell=0.128
		boxcar=0.512
		data_format="xdr_float"



Cat3d:   arustam@oas.stanford.edu   Mon Aug  6 09:14:13 2018
		sets next: in="/homes/sep/arustam/scratch/Cat3d@0nHzFa"
		axis=2
		file1="./test/w1.H"
		file2="./test/w1.H"
		junkME=0
	n2=2  o2=0.000000  d2=1.000000
		gff="-1"
		hff="-1"
hff=-1 gff=-1  n3=1  n4=1  n5=1  n6=1  n7=1  n8=1  n9=1 
	n1=200  o1=0.000000  d1=0.002000   label1="Undefined"   unit1="Undefined"
		hff="-1"
		gff="-1"
		esize=4
		data_format="xdr_float"



bin/Shaping.x:   arustam@oas.stanford.edu   Mon Aug  6 09:14:13 2018
		sets next: in="/homes/sep/arustam/scratch/Shaping.x@n2amhc"
	 	n1=121 o1=-0.14 d1=0.002 label1="Undefined" 

	 	n2=2 o2=0 d2=1 label2="" 

	 	n3=1 o3=0 d3=1 label3="none" 

	 	n4=1 o4=0 d4=1 label4="none" 

	 	n5=1 o5=0 d5=1 label5="none" 

	 	n6=1 o6=0 d6=1 label6="none" 

	 	n7=1 o7=0 d7=1 label7="none" 

	 	n8=1 o8=0 d8=1 label8="none" 

		data_format="xdr_float"

