Input from a tty

Gauss:   arustam@oas.stanford.edu   Sun Aug  5 21:13:57 2018
		sets next: in="/homes/sep/arustam/scratch/Gauss@uPLJ6x"
		From par: n1=50
		From par: n2=2
		From par: n3=1
		From par: ngauss=1
		From par: velback=0
		From par: o1=0
		From par: o2=0
		From par: o3=0
		From par: d1=1
		From par: d2=1
		From par: d3=1
	 	n1=50 o1=0 d1=1 label1="" 

	 	n2=2 o2=0 d2=1 label2="" 

	 	n3=1 o3=0 d3=1 label3="" 

		Read  from param: #zero_at=1e+17
	 	n1=50 o1=0 d1=1 label1="" 

	 	n2=2 o2=0 d2=1 label2="" 

	 	n3=1 o3=0 d3=1 label3="" 

		data_format="xdr_float"


bin/Shaping.x:   arustam@oas.stanford.edu   Sun Aug  5 21:13:57 2018
		sets next: in="/homes/sep/arustam/scratch/Shaping.x@0BaUxA"
	 	n1=4 o1=-1 d1=1 label1="Undefined" 

	 	n2=2 o2=0 d2=1 label2="" 

	 	n3=1 o3=0 d3=1 label3="none" 

	 	n4=1 o4=0 d4=1 label4="none" 

	 	n5=1 o5=0 d5=1 label5="none" 

	 	n6=1 o6=0 d6=1 label6="none" 

	 	n7=1 o7=0 d7=1 label7="none" 

	 	n8=1 o8=0 d8=1 label8="none" 

		data_format="xdr_float"

