Input from a tty

Wavelet:   arustam@oas.stanford.edu   Mon Aug  6 09:14:13 2018
		sets next: in="/homes/sep/arustam/scratch/Wavelet@dTdtA7"
		n2=1
		n3=1
		o1=0
	Wavelet generation
		esize=4
		ascii="n"
		given n1=200
	given n1 not a power of 2, new n1 computed

		computed n1=256
		d1=0.002
		n1=200
		domain="time"
		n1wavelet=256
		d1wavelet=0.002
		domainwavelet="time"
		wavelet="ricker2"
		phase="minimum"
		degrees=0
		fund=40
		flow=10
		fhigh=60
		order=6
		orderlow=6
		orderhigh=6
		tdelay=0
		bell=0.128
		boxcar=0.512
		data_format="xdr_float"

