//
// /home/repo/operator/src/lanczos_kernel.h
// (Header automatically generated by the ispc compiler.)
// DO NOT EDIT THIS FILE.
//

#pragma once
#include <stdint.h>



#ifdef __cplusplus
namespace ispc { /* namespace */
#endif // __cplusplus

#ifndef __ISPC_ALIGN__
#if defined(__clang__) || !defined(_MSC_VER)
// Clang, GCC, ICC
#define __ISPC_ALIGN__(s) __attribute__((aligned(s)))
#define __ISPC_ALIGNED_STRUCT__(s) struct __ISPC_ALIGN__(s)
#else
// Visual Studio
#define __ISPC_ALIGN__(s) __declspec(align(s))
#define __ISPC_ALIGNED_STRUCT__(s) __ISPC_ALIGN__(s) struct
#endif
#endif


///////////////////////////////////////////////////////////////////////////
// Functions exported from ispc code
///////////////////////////////////////////////////////////////////////////
#if defined(__cplusplus) && (! defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C )
extern "C" {
#endif // __cplusplus
    extern void lanczos_adj(int32_t ib1, int32_t ie1, float filter3, float filter2, float * filter1, float * mod_re, float * dat_re);
    extern void lanczos_adj_2d(int32_t ib1, int32_t ie1, float filter2, float * filter1, float * mod_re, float * dat_re);
    extern void lanczos_fwd(int32_t ib1, int32_t ie1, float filter3, float filter2, float * filter1, float * mod_re, float * dat_re);
    extern void lanczos_fwd_2d(int32_t ib1, int32_t ie1, float filter2, float * filter1, float * mod_re, float * dat_re);
#if defined(__cplusplus) && (! defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C )
} /* end extern C */
#endif // __cplusplus


#ifdef __cplusplus
} /* namespace */
#endif // __cplusplus
