Input from a tty

Spike:   bsc21964@login1   Tue Sep 10 15:15:38 2019
		sepstr_ready_out() : sets next in="stdin"
		n1=30
		n2=200
		n3=1
		n4=1
		n5=1
		n6=1
		n7=1
		o1=0
		o2=0
		o3=0
		o4=0
		o5=0
		o6=0
		o7=0
		d1=10
		d2=10
		d3=1
		d4=0.1
		d5=0.1
		d6=0.1
		d7=0.1
		label1="sec"
		label2="km"
		label3="km"
		label4="km"
		label5="km"
		title="Impulsive_plane_wave"
		esize=4
		data_format="xdr_float"


Pad:   bsc21964@login1   Tue Sep 10 15:15:38 2019
		sepstr_ready_out() : sets next in="stdin"
	 	n1=30 o1=0 d1=10 label1="" 

	 	n2=300 o2=-500 d2=10 label2="" 

		#beg=50
		#end=50
		data_format="xdr_float"


Transp:   bsc21964@login1   Tue Sep 10 15:15:38 2019
		sets next: in="/home/bsc21/bsc21964/scratch/dslow.H@"
Transposing plane 1 and 2 
Using 1000 megabytes 
		junkME=0
	n2=30  o2=0.000000  d2=10.000000   unit2="Undefined"
	n3=1  o3=0.000000  d3=1.000000   label3="km"   unit3="Undefined"
	n4=1  o4=0.000000  d4=0.100000   label4="km"   unit4="Undefined"
	n5=1  o5=0.000000  d5=0.100000   label5="km"   unit5="Undefined"
	n6=1  o6=0.000000  d6=0.100000   label6="Undefined"   unit6="Undefined"
	n7=1  o7=0.000000  d7=0.100000   label7="Undefined"   unit7="Undefined"
		gff="-1"
		hff="-1"
hff=-1 gff=-1  n9=1 
	n1=300  o1=-500.000000  d1=10.000000   unit1="Undefined"
		hff="-1"
		gff="-1"
		esize=4
		data_format="xdr_float"
