Input from a tty

Spike:   root@09889b02232e   Fri Feb 14 01:13:06 2020
		sepstr_ready_out() : sets next in="stdin"
		n1=1500
		n2=1
		n3=1
		n4=1
		n5=1
		n6=1
		n7=1
		o1=0
		o2=0
		o3=0
		o4=0
		o5=0
		o6=0
		o7=0
		d1=0.002
		d2=0.1
		d3=0.1
		d4=0.1
		d5=0.1
		d6=0.1
		d7=0.1
		label1="sec"
		label2="km"
		label3="km"
		label4="km"
		label5="km"
		title="Impulsive_plane_wave"
		esize=4
		data_format="xdr_float"


Bandpass:   root@09889b02232e   Fri Feb 14 01:13:06 2020
		sets next: in="/home/user/projects/scr/wave.H@"
		flo=10
		fhi=20
		nplo=6
		nphi=6
		phase=0
		data_format="xdr_float"

