TARGET = libOperator.a
.PHONY: default
	default: $(TARGET);

SRCDIR:=./src
BIN:=./bin
BUILDDIR:=./build

CC:=g++ -fopenmp -std=c++11 -fpic -O2 -ffast-math
SRCEXT:=cpp

REPO:=/home/user/project/repository.dev

SEPVECINC := -I/opt/genericIO/include -I/opt/SEP/include -I/opt/hypercube/include -I/opt/sepVector/include -I${REPO}/complex/include
SEPVECLIBS := -L/opt/hypercube/lib -L/opt/sepVector/lib -L/opt/genericIO/lib -L/opt/SEP/lib -L${REPO}/complex/lib -lcomplexHyper -lgenericCpp -lsepVector -lhypercube -lsep3d -lsep

# SEPVECINC:=-I/sep/gbarnier/genericIO/include -I/opt/SEP/SEP8.1/include -I${REPO}/complex/include
# SEPVECLIBS:=-L/sep/gbarnier/genericIO/lib -L/opt/SEP/SEP8.1/lib -L${REPO}/complex/lib -lcomplexHyper -lgenericCpp -lsepVector -lhypercube -lsep3d -lsep  

MYINC:=-I include
MYLIB:=lib

FFTWINC:=-I/opt/FFTW/include
FFTWLIB:=-L/opt/FFTW/lib -lfftw3f -lm

SOURCES:=$(shell find $(SRCDIR) -type f -name "*.$(SRCEXT)")
OBJECTS:=$(patsubst $(SRCDIR)/%,$(BUILDDIR)/%,$(SOURCES:.$(SRCEXT)=.o))


$(BUILDDIR)/%.o: $(SRCDIR)/%.$(SRCEXT)
	@mkdir -p $(BUILDDIR)
	@echo " $(CC) $(SEPVECINC) $(MYINC) -c -o $@ $<"; $(CC) $(SEPVECINC) $(MYINC) $(FFTWINC) $< $(SEPVECLIBS) $(FFTWLIB) -c -o$@

${TARGET}: ${OBJECTS}
	@mkdir -p ${MYLIB}
	@echo "Creating $@"...; 
	ar rcs ${MYLIB}/$@ $?

test/check%.x: test/check%.cpp
	$(CC) $(SEPVECINC) $(MYINC) $(FFTWINC) $< -L./lib -lOperator $(SEPVECLIBS) $(FFTWLIB) -o $@	
